name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar \
        -Dsonar.projectKey=Java-WebApp \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${SONAR_TOKEN}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with tags
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/WebApp:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/WebApp:latest ${{ secrets.DOCKER_USERNAME }}/my-app:1.0

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/WebApp:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/WebApp:1.0
